/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2016-11-27

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/
//Includes

#define ARM_MATH_CM3
#undef A0
#undef A1
#undef A2
#include <arm_math.h>

#include <functions.h>
#include <communication/usart.h>
#include <device_libraries/MPU_9250.h>
#include <device_libraries/motor_control.h>
#include <communication/rx.h>


/* Private typedef */


/* Private define  */

/* Private macro */

/* Private variables */

uint64_t c;

/* Private function prototypes */

/* Private functions */
/*
arm_pid_instance_f32 PID;
a toto
 duty = arm_pid_f32(&PID, pid_error);*/


/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	/*initializations*/
 	init_delay();
	motor_init();
	usart_init();
	functions_init();

	if(mpu9250_init(1,BITS_DLPF_CFG_188HZ)){  //INIT the mpu9250
    	USART_send_function("\nCouldn't initialize MPU9250 via SPI!\r");
    }
    else
    	USART_send_function("\nMPU9250 WAS SUCCESFULLY INITIALIZED!\r");

	calib_acc();
    delay_ms(500);

    GPIO_InitTypeDef GPIO_InitStruct;
	GPIO_InitStruct.GPIO_Pin = GPIO_Pin_10;
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStruct.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_40MHz;
	GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_Init(GPIOA, &GPIO_InitStruct);

    //sampling
    TIM5_sampling_timer(moveing_average_sampling*1000);
    delay_ms(moveing_average_sampling*1000*moveing_average_samples);
    //integrating
    TIM4_integrating_timer(angle_sampling*1000);

    delay_ms(1000);
    //motor_start();
    //BLDC_Regulator_calibration();
	while(1)
	{

		//USART_send_function_number(desired_yaw);
        //PID_roll_control(roll);
		//USART_send_function_number(TIM2->CCR3);

	}
	return 0;
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}
